# Generated by Django 4.1.2 on 2022-10-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_alter_user_managers_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='creation_datetime',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Полное имя пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Уникальное имя пользователя'),
        ),
    ]
