# Generated by Django 4.1.2 on 2022-10-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_rename_datetime_added_message_datetime_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default=1, max_length=30, verbose_name='Название чата'),
            preserve_default=False,
        ),
    ]
