# Generated by Django 4.1.2 on 2022-10-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_chat_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
