# Generated by Django 4.1.2 on 2022-10-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_delete_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='chatmember',
            options={'verbose_name': 'Участник чата', 'verbose_name_plural': 'Участники чата'},
        ),
    ]
