# Generated by Django 4.1.2 on 2022-11-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_alter_chatmember_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.CharField(default=1, max_length=50, verbose_name='Описание чата'),
            preserve_default=False,
        ),
    ]
