# Generated by Django 4.1.2 on 2022-11-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_chat_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMember',
        ),
    ]
