# Generated by Django 4.1.2 on 2022-10-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_creation_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Информация о пользователе', 'verbose_name_plural': 'Информация о пользователях'},
        ),
    ]
