# Generated by Django 4.1.2 on 2022-10-25 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор чата')),
                ('creation_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания чата')),
                ('first_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='Идентификатор пользователя 1')),
            ],
            options={
                'verbose_name': 'Чат',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор сообщения')),
                ('message_text', models.TextField(verbose_name='Сообщение')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время сообщения')),
                ('status', models.SmallIntegerField(verbose_name='Статус прочитанности сообщения')),
                ('chat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chats.chat', verbose_name='Идентификатор чата')),
                ('sender', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Идентификатор отправителя')),
            ],
            options={
                'verbose_name': 'Сообщение',
            },
        ),
    ]
