# Generated by Django 4.1.2 on 2022-10-25 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='first_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user', verbose_name='Идентификатор пользователя 1'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chat', verbose_name='Идентификатор чата'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Идентификатор отправителя'),
        ),
    ]
