# Generated by Django 4.1.2 on 2022-10-25 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('chats', '0002_alter_chat_first_user_alter_message_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='first_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Идентификатор пользователя 1'),
        ),
    ]
