# Generated by Django 4.1.2 on 2022-10-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_rename_creation_datetime_chat_datetime_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='datetime_added',
            new_name='datetime_sent',
        ),
    ]
