# Generated by Django 4.1.2 on 2022-10-30 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0008_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('datetime_sent', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время сообщения')),
                ('status', models.CharField(choices=[('DE', 'Delivered'), ('RE', 'Read')], max_length=10, verbose_name='Статус сообщения')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chats.chat', verbose_name='Идентификатор чата')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Идентификатор отправителя')),
            ],
            options={
                'verbose_name': 'Сообщение',
            },
        ),
    ]
