# Generated by Django 4.1.2 on 2022-10-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_alter_message_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
