# Generated by Django 4.1.2 on 2022-10-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['chat_id'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
