# Generated by Django 4.1.2 on 2022-10-30 10:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0004_rename_message_text_message_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='creation_datetime',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='chatmember',
            old_name='adding_datetime',
            new_name='datetime_added',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='adding_datetime',
            new_name='datetime_added',
        ),
        migrations.AlterUniqueTogether(
            name='chatmember',
            unique_together={('user', 'chat')},
        ),
    ]
