# Generated by Django 4.1.2 on 2022-10-30 18:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0009_alter_chat_options_alter_chatmember_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatmember',
            unique_together={('chat', 'user')},
        ),
    ]
